### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Shelly7w7** [JackMD/Repair#1]
Add compitability with economy👍

**Comment by Ifera** [comment]
I was going to do thay before releasing but got lazy. Will be implementing it soon.

**Comment by Haxley** [comment]
I suggest adding support for it to be cast on other players besides self. I.e.  /repair <all|hand> <default self|player>. Also, is this plugin compatible with EssentialsPE? I've customized Essentials repair command to be cast on other players, but I'd rather not have to modify it every time I update Essentials.

**Comment by GithubPaul1** [comment]
Will the update for compatibility with Economy still be released?

**Comment by mikeygio10** [comment]
...

**Comment by mrpwes** [comment]
...

**Comment by Ifera** [comment]
No!
